import { wrap } from 'module';
import { StyleSheet, Platform } from 'react-native';
import { hth, wth } from '../../constants/size';

const scheduleCompStyles = (theme: any) => {
  return StyleSheet.create({
    screenBackground: theme.background,
    container: {
      flex: 1,
      flexDirection: 'column',
      backgroundColor: theme.background,
      padding: wth(7),
      paddingTop: 0,
      paddingHorizontal: 5,
      // paddingTop: hth(10),
      flexGrow: wth(100),
    },
    titleRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      paddingHorizontal: 1,
    },
    titleText: {
      color: '#ffffff',
      fontSize: 30,
      fontWeight: 'bold',
      textAlign: 'center',
      lineHeight: 40,
    },
    subtitleText: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 19,
      padding: 20,
      textAlign: 'center',
      lineHeight: 30,
    },
    noScheduleImg: {
      width: 100,
      height: 100,
      margin: 20,

    },
    imageView: {
      flexDirection: 'row',
      justifyContent: 'center',
      justifySelf:'center',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      borderRadius: 15,
      paddingHorizontal: Platform.OS == 'ios' ? 10 : 30,
      marginTop: Platform.OS == 'ios' ? 80 : 40,
      paddingVertical:30,
      width: 200,
      marginBottom:20,
      // marginHorizontal: 90,
      // marginVertical: 60,
      borderWidth: 2,
      borderColor: 'rgba(255, 255, 255, 0.34)',
      borderStyle: 'dashed',
    },
    scheduleCard: {
      border: '1px solid rgba(255, 255, 255, 0.08)',
      flex: 1,
    },
    sectionTitleContainer: {
      paddingVertical: Platform.OS == 'ios' ? 15 : -45,
      backgroundColor: theme.background,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    card: {
      width: '95%',
      marginVertical: 5,
      //borderColor: 'rgba(255, 255, 255, 0.08)',
      margin: 10,
      borderRadius: 6,
      alignItems: 'flex-end',
    },
    contentBlock: {
      backgroundColor: theme.background,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      width: '98%',
      borderTopRightRadius: 6,
      borderBottomRightRadius: 6,
    },
    cardContentBlock: {
      borderColor: 'rgba(255, 255, 255, 0.08)',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderLeftWidth: 0,
      width: '100%',
      paddingTop: 6,
      paddingBottom: 2,
      paddingHorizontal: 12,
      borderTopRightRadius: 6,
      borderBottomRightRadius: 6,
    },
    dolls: {
      paddingTop: 5,
      paddingBottom: 5,
      paddingHorizontal: 12,
      color: 'rgba(255, 255, 255, 0.6)',
      backgroundColor: 'rgba(4, 8, 9, 0.88)',
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderWidth: 1,
      borderRadius: 16,
      marginRight: 10,
    },
    dollsText: {
      color: 'rgba(255, 255, 255, 0.6)',
      textAlign: 'center',
    },
    language: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: 3,
      paddingRight: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.13)',
      borderRadius: 16,
      borderColor: '#fff',
    },
    workMode: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.13)',
      borderRadius: 16,
      borderColor: '#fff',
    },
    languageText: {
      color: '#ffffff',
      textAlign: 'center',
      fontWeight: '600',
      fontSize: 12
    },
    usRow: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    scheduleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 0,
    },
    cardTime: {
      color: 'rgba(255, 255, 255, 0.6)',
      textAlign: 'left',
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 5,
      marginTop: 0,
    },

    cardTimeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      borderWidth: 1,
      paddingVertical: 18,
      paddingHorizontal: 10,
      borderRadius: 6,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      marginVertical: 15,
      textAlign: 'center',
      color: 'rgba(255, 255, 255, 0.2)',
    },
    timeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderRadius: 6,
      marginVertical: 5,
      textAlign: 'center',
      color: 'rgba(255, 255, 255, 0.2)',
    },
    cardTitle: {
      color: 'white',
      fontSize: 22,
      fontWeight: 'bold',
    },

    timer: {
      color: 'gray',
      padding: 0,
      margin: 0,
      fontSize: 16,
      marginBottom: 5,
      marginTop: 0,
    },
    dateOptions: {
      color: 'white',
      paddingVertical: 5,
      paddingLeft: 10,
      fontSize: 16,
      fontWeight: '600',
    },
    weekday: {
      opacity: 0.7,
      fontSize: 16,
      textAlign: 'right',
      marginLeft: 5,
      color: 'rgba(255, 255, 255, 0.4)',
    },
    date: {
      color: 'white',
      opacity: 0.7,
      fontSize: 16,
    },
    weekdayView: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    cardDetailsContainer: {
      paddingHorizontal: 20,
      paddingVertical: 30
    },
    cardDetailsTitle: {
      color: 'white',
      fontSize: 28,
      fontWeight: 'bold',
      lineHeight: 36,
      paddingRight: 10
    },
    cardDetailsSubTitle: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 18,
      fontWeight: 'bold',
    },
    cardDetailsLocation: {
      color: '#78ADF9',
      fontSize: 18,
      fontWeight: '500',
      lineHeight: 22,
      width: 232,
      flexWrap: 'wrap',
      alignSelf: 'flex-start',
    },
    timeZone: {
      color: '#rgba(255, 255, 255, 0.6)',
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 22,
    },
    coloredLanguageText: {
      color: '#78ADF9',
      fontWeight: '600',
    },
    coloredLanguage: {
      backgroundColor: 'rgba(96, 155, 240, 0.21)',
      textAlign: 'center',
    },
    logoImage: {
      height: 12,
      width: 16,
      marginRight: 5,
    },

    clockImage: {
      height: 18,
      width: 18,
    },
    arrowImage: {
      height: 28,
      width: 28,
    },
    checkImage: {
      height: 22,
      width: 22,
    },
    usImage: {
      height: 21,
      width: 21,
    },
    logoRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    text: {
      textAlign: 'center',
      color: 'rgba(255, 255, 255, 0.2)',
      fontSize: 20,
      fontWeight: '500',
    },
    buttonContainer: {
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 18,
      borderRadius: 6,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      marginVertical: 35,
      textAlign: 'center',
      color: 'rgba(255, 255, 255, 0.2)',
    },
    shiftContainer: {
      boxSizing: 'border-box',
      flexDirection: 'column',
      marginVertical: 40,
      padding: 15,
      height: 134,
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 8,
    },
    shiftRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 10,
    },
    shiftTime: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    shiftText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '500',
    },
    shiftTimeText: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 18,
      fontWeight: '400',
    },
  });
};

export default scheduleCompStyles;
