name: Android CI

on:
  push:
    branches: [ "sprint" ]
  pull_request:
    branches: [ "sprint" ]

jobs:
  BUILD:
    name: Build Android apk
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11 
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
        cd android
        chmod +x gradlew
        
    - name: Build with Gradle
      run: | 
        cd android 
        npm install --legacy-peer-deps
        npm install @react-native-community/cli-platform-android --legacy-peer-deps
        ./gradlew clean
        ./gradlew app:assembleRelease
    
  JEST:
    name: Run JEST Tests
    runs-on: ubuntu-latest
    needs: [BUILD]
    steps:
    - uses: actions/checkout@v3
    - name: Run Jest Tests
      run: | 
        npm install --force
  #      npm run test:unit
    
  FASTLANE:
    name: Publish Android Build through Fastlane
    runs-on: ubuntu-latest
    needs: [BUILD, JEST]
    steps:
    - uses: actions/checkout@v3
        
    - name: Fastlane
      run: | 
        sudo gem install fastlane
        cd fastlane
        fastlane android beta
  #      env:
  #        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
