export type IPermission =
    | 'AlphaBeta_Modify'
    | 'ConfirmedSchedule_Adjustment'
    | 'BiddingCycle_Modify'
    | 'BiddingCycle_View'
    | 'Bids_Modify'
    | 'Bids_View'
    | 'CA_Closure_Modify'
    | 'CalendarOverrideDays_Edit'
    | 'CalendarOverrideDays_View'
    | 'Center_Modify'
    | 'Center_View'
    | 'CenterAdvanced_Modify'
    | 'CenterAdvanced_View'
    | 'ConfirmedSchedule_Modify'
    | 'Debug_Modify'
    | 'FeatureFlag_Administrator'
    | 'Forecast_Administrator'
    | 'Forecast_Modify_ReviewPage'
    | 'Forecast_Publish_ReviewPage'
    | 'Forecast_View_ForecastsLP'
    | 'Forecast_View_Reports'
    | 'Forecast_View_ReviewPage'
    | 'GlobalSettings_Modify'
    | 'IntegrationSettings_Modify'
    | 'HoursBank_Modify'
    | 'HoursBank_View'
    | 'IntegrationSettings_Modify'
    | 'MenuCollapsed_View'
    | 'MenuProfile_View'
    | 'MenuReports_View'
    | 'MenuSettings_View'
    | 'Message_Create'
    | 'Message_Delete'
    | 'Message_Full'
    | 'Message_Modify'
    | 'Message_View'
    | 'NotificationTemplate_Create'
    | 'NotificationTemplate_Delete'
    | 'NotificationTemplate_Edit'
    | 'NotificationTemplate_View'
    | 'Organization_Modify'
    | 'Organization_View'
    | 'Premium_Modify'
    | 'ProposedSchedule_Confirm'
    | 'ProposedSchedule_Modify'
    | 'ProposedSchedule_Regenerate'
    | 'ProposedSchedule_View'
    | 'QueueGroup_Modify'
    | 'QueueGroup_View'
    | 'Report_SubHistory'
    | 'SetScheduleCycle_Modify'
    | 'SetScheduleCycle_View'
    | 'SetScheduleRequest_App&Dec'
    | 'SetScheduleRequest_Confirm'
    | 'SetScheduleRequest_Modify'
    | 'SetScheduleRequest_View'
    | 'SubbingBoard_AcceptSub'
    | 'SubbingBoard_Administrator'
    | 'SubbingBoard_Closure_Modify'
    | 'SubbingBoard_Delete'
    | 'SubbingBoard_Withdraw'
    | 'SuperOpsAnalyzer_DistDayPanel'
    | 'SuperOpsAnalyzer_EvicastPanel'
    | 'SuperOpsAnalyzer_ForecastHist'
    | 'SuperOpsAnalyzer_QueueModeler'
    | 'SuperOpsAnalyzer_SinstaPanel'
    | 'SuperOpsAnalyzer_StafferPanel'
    | 'UserAdvanced_Modify'
    | 'UserAdvanced_View'
    | 'UserBasic_Modify'
    | 'UserBasic_View'
    | 'UserInactive_View'
    | 'UserInactive_Modify'
    | 'UserRanking_Modify'
    | 'UserRanking_View'
    | 'UserRecord_Modify'
    | 'UserRoles_Modify'
    | 'UserRoles_View'
    | 'WorkRule_Modify'
    | 'WorkRule_View'
    | 'MenuExtended_View'
    | 'NOT_ANONYMOUS';

export const permissionsLookup = {
    alphaBetaModify: 'AlphaBeta_Modify',
    biddingCycleModify: 'BiddingCycle_Modify',
    biddingCycleView: 'BiddingCycle_View',
    bidsModify: 'Bids_Modify',
    bidsView: 'Bids_View',
    cAClosureModify: 'CA_Closure_Modify',
    calendarOverrideDaysEdit: 'CalendarOverrideDays_Edit',
    calendarOverrideDaysView: 'CalendarOverrideDays_View',
    centerModify: 'Center_Modify',
    centerView: 'Center_View',
    centerAdvancedModify: 'CenterAdvanced_Modify',
    centerAdvancedView: 'CenterAdvanced_View',
    confirmedScheduleModify: 'ConfirmedSchedule_Modify',
    debugModify: 'Debug_Modify',
    featureFlagAdmin: 'FeatureFlag_Administrator',
    forecastAdmin: 'Forecast_Administrator',
    forecastModifyReviewPage: 'Forecast_Modify_ReviewPage',
    forecastPublishReivewPage: 'Forecast_Publish_ReviewPage',
    forecastViewForecastsLP: 'Forecast_View_ForecastsLP',
    forecastViewReports: 'Forecast_View_Reports',
    forecastViewReviewPage: 'Forecast_View_ReviewPage',
    globalSettingsModify: 'GlobalSettings_Modify',
    integrationSettingsModify: 'IntegrationSettings_Modify',
    menuCollapsedView: 'MenuCollapsed_View',
    menuProfileView: 'MenuProfile_View',
    menuReportsView: 'MenuReports_View',
    menuSettingsView: 'MenuSettings_View',
    messageCreate: 'Message_Create',
    messageDelete: 'Message_Delete',
    messageFull: 'Message_Full',
    messageModify: 'Message_Modify',
    messageView: 'Message_View',
    notificationTemplateCreate: 'NotificationTemplate_Create',
    notificationTemplateDelete: 'NotificationTemplate_Delete',
    notificationTemplateEdit: 'NotificationTemplate_Edit',
    notificationTemplateView: 'NotificationTemplate_View',
    organizationModify: 'Organization_Modify',
    organizationView: 'Organization_View',
    premiumModify: 'Premium_Modify',
    proposedScheduleConfirm: 'ProposedSchedule_Confirm',
    proposedScheduleModify: 'ProposedSchedule_Modify',
    proposedScheduleRegenerate: 'ProposedSchedule_Regenerate',
    proposedScheduleView: 'ProposedSchedule_View',
    queueGroupModify: 'QueueGroup_Modify',
    queueGroupView: 'QueueGroup_View',
    reportSubHistory: 'Report_SubHistory',
    setScheduleCycleModify: 'SetScheduleCycle_Modify',
    setScheduleCycleView: 'SetScheduleCycle_View',
    setScheduleRequestAppAtDec: 'SetScheduleRequest_App&Dec',
    setScheduleRequestConfirm: 'SetScheduleRequest_Confirm',
    setScheduleRequestModify: 'SetScheduleRequest_Modify',
    setScheduleRequestView: 'SetScheduleRequest_View',
    subbingBoardAcceptSub: 'SubbingBoard_AcceptSub',
    subbingBoardAdmin: 'SubbingBoard_Administrator',
    subbingBoardClosureModify: 'SubbingBoard_Closure_Modify',
    subbingBoardDelete: 'SubbingBoard_Delete',
    subbingBoardWithdraw: 'SubbingBoard_Withdraw',
    superOpsAnalyzerDistDayPanel: 'SuperOpsAnalyzer_DistDayPanel',
    superOpsAnalyzerEvicastPanel: 'SuperOpsAnalyzer_EvicastPanel',
    superOpsAnalyzerForecastHist: 'SuperOpsAnalyzer_ForecastHist',
    superOpsAnalyzerQueueModeler: 'SuperOpsAnalyzer_QueueModeler',
    superOpsAnalyzerSinstaPanel: 'SuperOpsAnalyzer_SinstaPanel',
    superOpsAnalyzerStafferPanel: 'SuperOpsAnalyzer_StafferPanel',
    userAdvancedModify: 'UserAdvanced_Modify',
    userAdvancedView: 'UserAdvanced_View',
    userBasicModify: 'UserBasic_Modify',
    userBasicView: 'UserBasic_View',
    userInactiveView: 'UserInactive_View',
    userInactiveModify: 'UserInactive_Modify',
    userRankingModify: 'UserRanking_Modify',
    userRankingView: 'UserRanking_View',
    userRecordModify: 'UserRecord_Modify',
    userRolesModify: 'UserRoles_Modify',
    userRolesView: 'UserRoles_View',
    workRuleModify: 'WorkRule_Modify',
    workRuleView: 'WorkRule_View',
};
