name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "sprint" ]

jobs:
  BUILD:
    name: Build iOS apk
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build iOS
        run: |
          cd vital-interpreter-app-sprint
          npm install -legacy-peer-deps
          ls
          cd ios
          pod install
          npx react-native run-ios
          ls -al

  JEST:
    name: Run JEST Tests
    runs-on: ubuntu-latest
    needs: [BUILD]
    steps:
    - uses: actions/checkout@v3
    - name: Run Jest Tests
      run: | 
        cd vital-interpreter-app-sprint
        npm install --force
  #      npm run test:unit
  
  EAS:
    name: Run EAS CLI
    runs-on: ubuntu-latest
    needs: [BUILD, JEST]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup eas cli 
        run: |
          cd vital-interpreter-app-sprint
          npm install -g eas-cli
          ls
          pwd
  
